# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-11 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_up', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opsuser',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
