# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-13 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_up', '0002_auto_20161111_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='opsuser',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
