# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-13 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_up', '0003_opsuser_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='opsuser',
            name='vkey',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
